version: "1.0.3"
holoapi:
  hook: true
  offset: 3
on-death-to-monster-loss:
  percentage: false
  value: 150.0
on-death-to-player-loss:
  percentage: true
  value: 50.0
  killer-gains-losses: true
on-other-deaths:
  percentage: true
  value: 50.0