main: org.nunnerycode.bukkit.mobbountyreloaded.MobBountyReloadedPlugin
author: ToppleTheNun
version: ${project.build.version}
name: ${project.build.name}
depend: [Vault]
softdepend: [HoloAPI]

permissions:
  mobbountyreloaded.ignore-messages:
    default: false
  mobbountyreloaded.earn:
    default: true
  mobbountyreloaded.command.list:
    default: true

commands:
  mobbountyreloaded:
    aliases: [mbr]