main: org.nunnerycode.bukkit.mobbountyreloaded.MobBountyReloadedPlugin
author: ToppleTheNun
version: ${project.build.version}
name: ${project.build.name}
depend: [Vault]

permissions:
  mobbountyreloaded.earn:
    default: true
  mobbountyreloaded.command.list
    default: true

commands:
  mobbountyreloaded: